version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/carpick-355305/carpick:2.3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/carpick/src
    ports:
      - 3000:3000
